### ISSUE TITLE
Key bindings are not functioning correctly

### ISSUE THREAD

**Issue by ishaanrathodd** [svobs/iina-advance#3] opened 2024-07-31 16:48 UTC
**System and IINA version:**
- macOS Sequoia Beta 5.1
- IINA Advance 1.1 Build 2

**Expected behavior:**
features should work by the keyboard shortcuts assigned to them

**Actual behavior:**
If i have assigned left arrow to seek backward 5 secs, it seeking forward 10 secs. Even the space assigned to cycle pause is not responding at all.

**Steps to reproduce:**
I don't know, it started happening after installing advance for an hour. Maybe some settings are conflicting, i tried to toggle each one with no change.

**How often does this happen?**
Persistent

**Comment by ishaanrathodd** [comment] 2024-08-13 10:28
@svobs are you working on this bug? almost unusable as of now due to key bindings not working as expected

**Comment by svobs** [comment] 2024-08-14 05:53
This looks like [IINA issue 4651](https://github.com/iina/iina/issues/4651), which is also logged in [mpv issue 12047](https://github.com/mpv-player/mpv/issues/12047), which ultimately points to [this FFmpeg bug](https://trac.ffmpeg.org/ticket/10585).

Because this is open-source software and it's built on other open-source components, it can get tricky to upgrade a single component before everything else is ready to work with it. It can also be hard to fix individual bugs in those other components on an a-la-carte basis, although not impossible.

Make sure you are including `exact` at the end of each key binding, like this:

<img width="280" alt="SCR-20240813-trwk" src="https://github.com/user-attachments/assets/52d68128-04b0-43d2-95c7-1ba7db6e87e6">

Let me know if that solves it.

**Comment by ishaanrathodd** [comment] 2024-08-14 06:47
> This looks like [IINA issue 4651](https://github.com/iina/iina/issues/4651), which is also logged in [mpv issue 12047](https://github.com/mpv-player/mpv/issues/12047), which ultimately points to [this FFmpeg bug](https://trac.ffmpeg.org/ticket/10585).
> 
> 
> 
> Because this is open-source software and it's built on other open-source components, it can get tricky to upgrade a single component before everything else is ready to work with it. It can also be hard to fix individual bugs in those other components on an a-la-carte basis, although not impossible.
> 
> 
> 
> Make sure you are including `exact` at the end of each key binding, like this:
> 
> 
> 
> <img width="280" alt="SCR-20240813-trwk" src="https://github.com/user-attachments/assets/52d68128-04b0-43d2-95c7-1ba7db6e87e6">
> 
> 
> 
> Let me know if that solves it.

okay yes it does solve the seek problem, but is there a fix for cycle pause? I'm using space as the key for it.

**Comment by svobs** [comment] 2024-08-14 08:18
> okay yes it does solve the seek problem, but is there a fix for cycle pause? I'm using space as the key for it.

I see above you said that you are using `SPACE` for `cycle pause` but it's not responding?

Make sure that it is the only binding mapped to `SPACE`. You can use the search field to help, like this:
<img width="932" alt="SCR-20240814-bzrz" src="https://github.com/user-attachments/assets/100add61-18ee-436b-9b2f-7a40be175f1d">
If there is a conflict which causes the binding to be disabled, the binding will be colored red with strikethrough. In that case, you'll need to either delete the other binding or change it to a different key.

**Comment by ishaanrathodd** [comment] 2024-08-14 08:36
@svobs  I did check, only one binding is allotted to space, yet not working.

**Comment by svobs** [comment] 2024-08-15 04:41
@ishaanrathodd can you post your config file here? You can use the `Show the config file in Finder` button to go to it, then drag & drop into your reply.

Some other troubleshooting:

1. Try changing `SPACE` to a different binding (like `cycle mute` and see if it works for that
2. Try adding another key (like `k`) for `cycle pause` and see if that works.

**Comment by ishaanrathodd** [comment] 2024-08-15 04:52
@svobs not able to post conf file here it isnt supported. About the cycle mute, it is working with space but cycle pause is neither working with space nor with any other key.

https://github.com/user-attachments/assets/7c340c50-0c89-4979-8f4e-41bf0f608f09

Here is the video recording of all configs

**Comment by svobs** [comment] 2024-08-15 19:21
Can't see any problems there... I'll have to take a look at a log file.

To enable logging follow these instructions (copied and modified from one of @low-batt's posts).

* Start IINA
* Click on  `Settings…` under the `IINA` menu
* The settings panel appears
* On the left side of the panel click on `Advanced`
* Slide the `Enable advanced settings` toggle button to be on (blue)
* Click on the checkbox `Enable logging to file`
* Confirm the settings panel looks like the screenshot below
* **Restart IINA** to activate logging
  ![enable-logging](https://private-user-images.githubusercontent.com/86170219/358012670-3dfd4017-b0a5-4077-a673-eefb9a8084f8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NDkwMzMsIm5iZiI6MTcyMzc0ODczMywicGF0aCI6Ii84NjE3MDIxOS8zNTgwMTI2NzAtM2RmZDQwMTctYjBhNS00MDc3LWE2NzMtZWVmYjlhODA4NGY4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDE5MDUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MjJkZjI3YWUxNDQ4NWZjNzZkY2NjMTAxY2MzNGU4M2Q4MWFiNzY3YzQxYWE5ODA2N2IxOTZkZjNlMTQ1Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hZT6DDs9Z-euYiiJLWqQWZ_wylhRg02Kqbci5PRklMw)

Once IINA has restarted, play the video for a few seconds, press space to try activate the key binding for pause, then let the video play for another few seconds before closing the window. Then:

* Click on  `Settings…` under the `IINA` menu
* The settings panel appears
* On the left side of the panel click on `Advanced`
* Click on `Open log directory`
* A new `Finder` window appears containing the logs for this session
* **Quit IINA** to complete the log files

The `Finder` window contains multiple files, `iina.log`, `pii.txt`, and one `mpv-*.log` for each player window. To attach the log files to this issue, drag-n-drop them from the `Finder` window to the `Leave a comment` section below. Include both the `iina.log` and the `mpv` log(s). Do not include the `pii.txt` because it contains information like the video name which most likely isn't important.

With logging enabled IINA creates a new log directory each time it is started. If accessing the logs using `Terminal` be sure to obtain them from the latest log directory.

**DO NOT FORGET** to disable logging once you have obtained log files for the problem being investigated. IINA does not restrict the size of log files or delete old logs. If you leave logging enabled the logs will continue to accumulate.

**Comment by ishaanrathodd** [comment] 2024-08-16 15:33
@svobs 
[iina.log](https://github.com/user-attachments/files/16638765/iina.log)
[mpv-13c0.log](https://github.com/user-attachments/files/16638770/mpv-13c0.log)
[mpv-14c0.log](https://github.com/user-attachments/files/16638771/mpv-14c0.log)

Does this work?

**Comment by svobs** [comment] 2024-08-17 20:33
Thank you for uploading those. It looks like the logs stop recording before the program was exited - looks like you disabled them again? - but I think I got enough to see that for some reason, the menu item for `Pause` / `Resume` is not getting triggered.

I don't know why this would be happening. The biggest suspect I can think of is some kind of bug or conflict with the system media keys handling.

Can you try deselecting `Use system media control` and then relaunching Advance?

<img width="580" alt="SCR-20240817-marp" src="https://github.com/user-attachments/assets/5da9869e-e5d4-4e0d-998f-2a9c251c4a28">

Let me know if the problem persists after that.

I do have an idea for how I might work around the problem, but it would be a significant code change, which would delay the 1.2 release a bit because I'm days away from releasing it now.

**Comment by ishaanrathodd** [comment] 2024-08-18 03:58
@svobs yep the problem persists even after disabling system media keys and relaunching the app. It's okay take your time but please so fix the bug, my primary reflex to pause the video is using key bindings and not trackpad so its kinda inconvenient haha

**Comment by svobs** [comment] 2024-08-27 22:24
@ishaanrathodd I made some changes to the key processing which hopefully should fix it, and I'm feeling lucky so I went ahead and posted release 1.2 with the changes. Please try it & confirm whether the issue is resolved for you.

**Comment by ishaanrathodd** [comment] 2024-08-28 03:53
@svobs That was really fast🫨 Works now! Great thanks!!

**Comment by svobs** [comment] 2024-08-28 19:39
> Works now! Great thanks!!

Great to hear! I will close this issue as fixed.

**Closed as completed by svobs** 2024-08-28 19:39 UTC
